// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFIXKs5YIfc0KP0cUezKywTa_8XFVKfRk',
    appId: '1:363704117925:web:b1f272bd6f8b7035c83b4c',
    messagingSenderId: '363704117925',
    projectId: 'employee-manager-6da28',
    authDomain: 'employee-manager-6da28.firebaseapp.com',
    storageBucket: 'employee-manager-6da28.firebasestorage.app',
    measurementId: 'G-MVZ8J51240',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4D-MaD1LHVdruYJHnF_gzBDB-64VlSxk',
    appId: '1:363704117925:android:c26e18f505af874fc83b4c',
    messagingSenderId: '363704117925',
    projectId: 'employee-manager-6da28',
    storageBucket: 'employee-manager-6da28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwL4Y3CS8gPSPiglYUDcwxw_W2zUvVf0w',
    appId: '1:363704117925:ios:90992d838bb6f288c83b4c',
    messagingSenderId: '363704117925',
    projectId: 'employee-manager-6da28',
    storageBucket: 'employee-manager-6da28.firebasestorage.app',
    iosBundleId: 'com.example.employeemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwL4Y3CS8gPSPiglYUDcwxw_W2zUvVf0w',
    appId: '1:363704117925:ios:90992d838bb6f288c83b4c',
    messagingSenderId: '363704117925',
    projectId: 'employee-manager-6da28',
    storageBucket: 'employee-manager-6da28.firebasestorage.app',
    iosBundleId: 'com.example.employeemanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFIXKs5YIfc0KP0cUezKywTa_8XFVKfRk',
    appId: '1:363704117925:web:44d99ee2cb8dae4dc83b4c',
    messagingSenderId: '363704117925',
    projectId: 'employee-manager-6da28',
    authDomain: 'employee-manager-6da28.firebaseapp.com',
    storageBucket: 'employee-manager-6da28.firebasestorage.app',
    measurementId: 'G-62W3J5JCW8',
  );
}
